// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/task_executor.proto

package taskexecutor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WriteConcernLevel int32

const (
	WriteConcernLevel_WRITE_CONCERN_LEVEL_UNSPECIFIED    WriteConcernLevel = 0
	WriteConcernLevel_WRITE_CONCERN_REPLICA_ACKNOWLEDGED WriteConcernLevel = 1
	WriteConcernLevel_WRITE_CONCERN_MAJORITY             WriteConcernLevel = 2
	WriteConcernLevel_WRITE_CONCERN_UNACKNOWLEDGED       WriteConcernLevel = 3
	WriteConcernLevel_WRITE_CONCERN_JOURNALED            WriteConcernLevel = 4
)

// Enum value maps for WriteConcernLevel.
var (
	WriteConcernLevel_name = map[int32]string{
		0: "WRITE_CONCERN_LEVEL_UNSPECIFIED",
		1: "WRITE_CONCERN_REPLICA_ACKNOWLEDGED",
		2: "WRITE_CONCERN_MAJORITY",
		3: "WRITE_CONCERN_UNACKNOWLEDGED",
		4: "WRITE_CONCERN_JOURNALED",
	}
	WriteConcernLevel_value = map[string]int32{
		"WRITE_CONCERN_LEVEL_UNSPECIFIED":    0,
		"WRITE_CONCERN_REPLICA_ACKNOWLEDGED": 1,
		"WRITE_CONCERN_MAJORITY":             2,
		"WRITE_CONCERN_UNACKNOWLEDGED":       3,
		"WRITE_CONCERN_JOURNALED":            4,
	}
)

func (x WriteConcernLevel) Enum() *WriteConcernLevel {
	p := new(WriteConcernLevel)
	*p = x
	return p
}

func (x WriteConcernLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WriteConcernLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_task_executor_proto_enumTypes[0].Descriptor()
}

func (WriteConcernLevel) Type() protoreflect.EnumType {
	return &file_proto_task_executor_proto_enumTypes[0]
}

func (x WriteConcernLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WriteConcernLevel.Descriptor instead.
func (WriteConcernLevel) EnumDescriptor() ([]byte, []int) {
	return file_proto_task_executor_proto_rawDescGZIP(), []int{0}
}

type RetryPolicyType int32

const (
	RetryPolicyType_RETRY_POLICY_TYPE_UNSPECIFIED RetryPolicyType = 0
	RetryPolicyType_RETRY_POLICY_CONSTANT         RetryPolicyType = 1
	RetryPolicyType_RETRY_POLICY_LINEAR           RetryPolicyType = 2
	RetryPolicyType_RETRY_POLICY_EXPONENTIAL      RetryPolicyType = 3
)

// Enum value maps for RetryPolicyType.
var (
	RetryPolicyType_name = map[int32]string{
		0: "RETRY_POLICY_TYPE_UNSPECIFIED",
		1: "RETRY_POLICY_CONSTANT",
		2: "RETRY_POLICY_LINEAR",
		3: "RETRY_POLICY_EXPONENTIAL",
	}
	RetryPolicyType_value = map[string]int32{
		"RETRY_POLICY_TYPE_UNSPECIFIED": 0,
		"RETRY_POLICY_CONSTANT":         1,
		"RETRY_POLICY_LINEAR":           2,
		"RETRY_POLICY_EXPONENTIAL":      3,
	}
)

func (x RetryPolicyType) Enum() *RetryPolicyType {
	p := new(RetryPolicyType)
	*p = x
	return p
}

func (x RetryPolicyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RetryPolicyType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_task_executor_proto_enumTypes[1].Descriptor()
}

func (RetryPolicyType) Type() protoreflect.EnumType {
	return &file_proto_task_executor_proto_enumTypes[1]
}

func (x RetryPolicyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RetryPolicyType.Descriptor instead.
func (RetryPolicyType) EnumDescriptor() ([]byte, []int) {
	return file_proto_task_executor_proto_rawDescGZIP(), []int{1}
}

type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_UNSPECIFIED TaskStatus = 0
	TaskStatus_TASK_STATUS_PENDING     TaskStatus = 1
	TaskStatus_TASK_STATUS_IN_PROGRESS TaskStatus = 2
	TaskStatus_TASK_STATUS_COMPLETED   TaskStatus = 3
	TaskStatus_TASK_STATUS_FAILED      TaskStatus = 4
	TaskStatus_TASK_STATUS_DLQ         TaskStatus = 5
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_STATUS_UNSPECIFIED",
		1: "TASK_STATUS_PENDING",
		2: "TASK_STATUS_IN_PROGRESS",
		3: "TASK_STATUS_COMPLETED",
		4: "TASK_STATUS_FAILED",
		5: "TASK_STATUS_DLQ",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_UNSPECIFIED": 0,
		"TASK_STATUS_PENDING":     1,
		"TASK_STATUS_IN_PROGRESS": 2,
		"TASK_STATUS_COMPLETED":   3,
		"TASK_STATUS_FAILED":      4,
		"TASK_STATUS_DLQ":         5,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_task_executor_proto_enumTypes[2].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_proto_task_executor_proto_enumTypes[2]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_task_executor_proto_rawDescGZIP(), []int{2}
}

// Task Management Messages
type AddTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutorName  string                 `protobuf:"bytes,1,opt,name=executor_name,json=executorName,proto3" json:"executor_name,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTaskRequest) Reset() {
	*x = AddTaskRequest{}
	mi := &file_proto_task_executor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTaskRequest) ProtoMessage() {}

func (x *AddTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_executor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTaskRequest.ProtoReflect.Descriptor instead.
func (*AddTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_task_executor_proto_rawDescGZIP(), []int{0}
}

func (x *AddTaskRequest) GetExecutorName() string {
	if x != nil {
		return x.ExecutorName
	}
	return ""
}

func (x *AddTaskRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AddTaskRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type AddTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTaskResponse) Reset() {
	*x = AddTaskResponse{}
	mi := &file_proto_task_executor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTaskResponse) ProtoMessage() {}

func (x *AddTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_executor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTaskResponse.ProtoReflect.Descriptor instead.
func (*AddTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_task_executor_proto_rawDescGZIP(), []int{1}
}

func (x *AddTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type GetTaskStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskStatusRequest) Reset() {
	*x = GetTaskStatusRequest{}
	mi := &file_proto_task_executor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskStatusRequest) ProtoMessage() {}

func (x *GetTaskStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_executor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskStatusRequest.ProtoReflect.Descriptor instead.
func (*GetTaskStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_task_executor_proto_rawDescGZIP(), []int{2}
}

func (x *GetTaskStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTaskStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        TaskStatus             `protobuf:"varint,1,opt,name=status,proto3,enum=taskexecutor.TaskStatus" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskStatusResponse) Reset() {
	*x = GetTaskStatusResponse{}
	mi := &file_proto_task_executor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskStatusResponse) ProtoMessage() {}

func (x *GetTaskStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_executor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskStatusResponse.ProtoReflect.Descriptor instead.
func (*GetTaskStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_task_executor_proto_rawDescGZIP(), []int{3}
}

func (x *GetTaskStatusResponse) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *GetTaskStatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Executor Management Messages
type RegisterExecutorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutorName  string                 `protobuf:"bytes,1,opt,name=executor_name,json=executorName,proto3" json:"executor_name,omitempty"`
	LeaderId      string                 `protobuf:"bytes,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterExecutorRequest) Reset() {
	*x = RegisterExecutorRequest{}
	mi := &file_proto_task_executor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterExecutorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterExecutorRequest) ProtoMessage() {}

func (x *RegisterExecutorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_executor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterExecutorRequest.ProtoReflect.Descriptor instead.
func (*RegisterExecutorRequest) Descriptor() ([]byte, []int) {
	return file_proto_task_executor_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterExecutorRequest) GetExecutorName() string {
	if x != nil {
		return x.ExecutorName
	}
	return ""
}

func (x *RegisterExecutorRequest) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

type RegisterExecutorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterExecutorResponse) Reset() {
	*x = RegisterExecutorResponse{}
	mi := &file_proto_task_executor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterExecutorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterExecutorResponse) ProtoMessage() {}

func (x *RegisterExecutorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_executor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterExecutorResponse.ProtoReflect.Descriptor instead.
func (*RegisterExecutorResponse) Descriptor() ([]byte, []int) {
	return file_proto_task_executor_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterExecutorResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetNextTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutorName  string                 `protobuf:"bytes,1,opt,name=executor_name,json=executorName,proto3" json:"executor_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNextTaskRequest) Reset() {
	*x = GetNextTaskRequest{}
	mi := &file_proto_task_executor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNextTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNextTaskRequest) ProtoMessage() {}

func (x *GetNextTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_executor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNextTaskRequest.ProtoReflect.Descriptor instead.
func (*GetNextTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_task_executor_proto_rawDescGZIP(), []int{6}
}

func (x *GetNextTaskRequest) GetExecutorName() string {
	if x != nil {
		return x.ExecutorName
	}
	return ""
}

type GetNextTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNextTaskResponse) Reset() {
	*x = GetNextTaskResponse{}
	mi := &file_proto_task_executor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNextTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNextTaskResponse) ProtoMessage() {}

func (x *GetNextTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_executor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNextTaskResponse.ProtoReflect.Descriptor instead.
func (*GetNextTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_task_executor_proto_rawDescGZIP(), []int{7}
}

func (x *GetNextTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type UpdateTaskStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        TaskStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=taskexecutor.TaskStatus" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskStatusRequest) Reset() {
	*x = UpdateTaskStatusRequest{}
	mi := &file_proto_task_executor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskStatusRequest) ProtoMessage() {}

func (x *UpdateTaskStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_executor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateTaskStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_task_executor_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateTaskStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTaskStatusRequest) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *UpdateTaskStatusRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UpdateTaskStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskStatusResponse) Reset() {
	*x = UpdateTaskStatusResponse{}
	mi := &file_proto_task_executor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskStatusResponse) ProtoMessage() {}

func (x *UpdateTaskStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_executor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateTaskStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_task_executor_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateTaskStatusResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

// Executor Configuration Messages
type CreateExecutorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *ExecutorConfig        `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExecutorRequest) Reset() {
	*x = CreateExecutorRequest{}
	mi := &file_proto_task_executor_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExecutorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExecutorRequest) ProtoMessage() {}

func (x *CreateExecutorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_executor_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExecutorRequest.ProtoReflect.Descriptor instead.
func (*CreateExecutorRequest) Descriptor() ([]byte, []int) {
	return file_proto_task_executor_proto_rawDescGZIP(), []int{10}
}

func (x *CreateExecutorRequest) GetConfig() *ExecutorConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type CreateExecutorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Executor      *Executor              `protobuf:"bytes,1,opt,name=executor,proto3" json:"executor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExecutorResponse) Reset() {
	*x = CreateExecutorResponse{}
	mi := &file_proto_task_executor_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExecutorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExecutorResponse) ProtoMessage() {}

func (x *CreateExecutorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_executor_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExecutorResponse.ProtoReflect.Descriptor instead.
func (*CreateExecutorResponse) Descriptor() ([]byte, []int) {
	return file_proto_task_executor_proto_rawDescGZIP(), []int{11}
}

func (x *CreateExecutorResponse) GetExecutor() *Executor {
	if x != nil {
		return x.Executor
	}
	return nil
}

type UpdateExecutorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Config        *ExecutorConfig        `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateExecutorRequest) Reset() {
	*x = UpdateExecutorRequest{}
	mi := &file_proto_task_executor_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateExecutorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExecutorRequest) ProtoMessage() {}

func (x *UpdateExecutorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_executor_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExecutorRequest.ProtoReflect.Descriptor instead.
func (*UpdateExecutorRequest) Descriptor() ([]byte, []int) {
	return file_proto_task_executor_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateExecutorRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateExecutorRequest) GetConfig() *ExecutorConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type UpdateExecutorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Executor      *Executor              `protobuf:"bytes,1,opt,name=executor,proto3" json:"executor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateExecutorResponse) Reset() {
	*x = UpdateExecutorResponse{}
	mi := &file_proto_task_executor_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateExecutorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExecutorResponse) ProtoMessage() {}

func (x *UpdateExecutorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_executor_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExecutorResponse.ProtoReflect.Descriptor instead.
func (*UpdateExecutorResponse) Descriptor() ([]byte, []int) {
	return file_proto_task_executor_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateExecutorResponse) GetExecutor() *Executor {
	if x != nil {
		return x.Executor
	}
	return nil
}

type GetExecutorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExecutorRequest) Reset() {
	*x = GetExecutorRequest{}
	mi := &file_proto_task_executor_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecutorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutorRequest) ProtoMessage() {}

func (x *GetExecutorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_executor_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutorRequest.ProtoReflect.Descriptor instead.
func (*GetExecutorRequest) Descriptor() ([]byte, []int) {
	return file_proto_task_executor_proto_rawDescGZIP(), []int{14}
}

func (x *GetExecutorRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetExecutorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Executor      *Executor              `protobuf:"bytes,1,opt,name=executor,proto3" json:"executor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExecutorResponse) Reset() {
	*x = GetExecutorResponse{}
	mi := &file_proto_task_executor_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecutorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutorResponse) ProtoMessage() {}

func (x *GetExecutorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_executor_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutorResponse.ProtoReflect.Descriptor instead.
func (*GetExecutorResponse) Descriptor() ([]byte, []int) {
	return file_proto_task_executor_proto_rawDescGZIP(), []int{15}
}

func (x *GetExecutorResponse) GetExecutor() *Executor {
	if x != nil {
		return x.Executor
	}
	return nil
}

type ListExecutorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExecutorsRequest) Reset() {
	*x = ListExecutorsRequest{}
	mi := &file_proto_task_executor_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExecutorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExecutorsRequest) ProtoMessage() {}

func (x *ListExecutorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_executor_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExecutorsRequest.ProtoReflect.Descriptor instead.
func (*ListExecutorsRequest) Descriptor() ([]byte, []int) {
	return file_proto_task_executor_proto_rawDescGZIP(), []int{16}
}

func (x *ListExecutorsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListExecutorsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListExecutorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Executors     []*Executor            `protobuf:"bytes,1,rep,name=executors,proto3" json:"executors,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExecutorsResponse) Reset() {
	*x = ListExecutorsResponse{}
	mi := &file_proto_task_executor_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExecutorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExecutorsResponse) ProtoMessage() {}

func (x *ListExecutorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_executor_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExecutorsResponse.ProtoReflect.Descriptor instead.
func (*ListExecutorsResponse) Descriptor() ([]byte, []int) {
	return file_proto_task_executor_proto_rawDescGZIP(), []int{17}
}

func (x *ListExecutorsResponse) GetExecutors() []*Executor {
	if x != nil {
		return x.Executors
	}
	return nil
}

func (x *ListExecutorsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// Удаление executor
type DeleteExecutorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExecutorRequest) Reset() {
	*x = DeleteExecutorRequest{}
	mi := &file_proto_task_executor_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExecutorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExecutorRequest) ProtoMessage() {}

func (x *DeleteExecutorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_executor_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExecutorRequest.ProtoReflect.Descriptor instead.
func (*DeleteExecutorRequest) Descriptor() ([]byte, []int) {
	return file_proto_task_executor_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteExecutorRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteExecutorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExecutorResponse) Reset() {
	*x = DeleteExecutorResponse{}
	mi := &file_proto_task_executor_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExecutorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExecutorResponse) ProtoMessage() {}

func (x *DeleteExecutorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_executor_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExecutorResponse.ProtoReflect.Descriptor instead.
func (*DeleteExecutorResponse) Descriptor() ([]byte, []int) {
	return file_proto_task_executor_proto_rawDescGZIP(), []int{19}
}

// Common Messages
type Executor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Enabled       bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Config        *ExecutorConfig        `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Executor) Reset() {
	*x = Executor{}
	mi := &file_proto_task_executor_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Executor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Executor) ProtoMessage() {}

func (x *Executor) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_executor_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Executor.ProtoReflect.Descriptor instead.
func (*Executor) Descriptor() ([]byte, []int) {
	return file_proto_task_executor_proto_rawDescGZIP(), []int{20}
}

func (x *Executor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Executor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Executor) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Executor) GetConfig() *ExecutorConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Executor) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Executor) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ExecutorConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	WriteConcern  *WriteConcern          `protobuf:"bytes,3,opt,name=write_concern,json=writeConcern,proto3" json:"write_concern,omitempty"`
	RetryPolicy   *RetryPolicy           `protobuf:"bytes,4,opt,name=retry_policy,json=retryPolicy,proto3" json:"retry_policy,omitempty"`
	DlqConfig     *DLQConfig             `protobuf:"bytes,5,opt,name=dlq_config,json=dlqConfig,proto3" json:"dlq_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutorConfig) Reset() {
	*x = ExecutorConfig{}
	mi := &file_proto_task_executor_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutorConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutorConfig) ProtoMessage() {}

func (x *ExecutorConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_executor_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutorConfig.ProtoReflect.Descriptor instead.
func (*ExecutorConfig) Descriptor() ([]byte, []int) {
	return file_proto_task_executor_proto_rawDescGZIP(), []int{21}
}

func (x *ExecutorConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExecutorConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ExecutorConfig) GetWriteConcern() *WriteConcern {
	if x != nil {
		return x.WriteConcern
	}
	return nil
}

func (x *ExecutorConfig) GetRetryPolicy() *RetryPolicy {
	if x != nil {
		return x.RetryPolicy
	}
	return nil
}

func (x *ExecutorConfig) GetDlqConfig() *DLQConfig {
	if x != nil {
		return x.DlqConfig
	}
	return nil
}

type WriteConcern struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         WriteConcernLevel      `protobuf:"varint,1,opt,name=level,proto3,enum=taskexecutor.WriteConcernLevel" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteConcern) Reset() {
	*x = WriteConcern{}
	mi := &file_proto_task_executor_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteConcern) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteConcern) ProtoMessage() {}

func (x *WriteConcern) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_executor_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteConcern.ProtoReflect.Descriptor instead.
func (*WriteConcern) Descriptor() ([]byte, []int) {
	return file_proto_task_executor_proto_rawDescGZIP(), []int{22}
}

func (x *WriteConcern) GetLevel() WriteConcernLevel {
	if x != nil {
		return x.Level
	}
	return WriteConcernLevel_WRITE_CONCERN_LEVEL_UNSPECIFIED
}

type RetryPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          RetryPolicyType        `protobuf:"varint,1,opt,name=type,proto3,enum=taskexecutor.RetryPolicyType" json:"type,omitempty"`
	MaxAttempts   int32                  `protobuf:"varint,2,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	Interval      *durationpb.Duration   `protobuf:"bytes,3,opt,name=interval,proto3" json:"interval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryPolicy) Reset() {
	*x = RetryPolicy{}
	mi := &file_proto_task_executor_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryPolicy) ProtoMessage() {}

func (x *RetryPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_executor_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryPolicy.ProtoReflect.Descriptor instead.
func (*RetryPolicy) Descriptor() ([]byte, []int) {
	return file_proto_task_executor_proto_rawDescGZIP(), []int{23}
}

func (x *RetryPolicy) GetType() RetryPolicyType {
	if x != nil {
		return x.Type
	}
	return RetryPolicyType_RETRY_POLICY_TYPE_UNSPECIFIED
}

func (x *RetryPolicy) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *RetryPolicy) GetInterval() *durationpb.Duration {
	if x != nil {
		return x.Interval
	}
	return nil
}

type DLQConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	QueueName     string                 `protobuf:"bytes,2,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DLQConfig) Reset() {
	*x = DLQConfig{}
	mi := &file_proto_task_executor_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DLQConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DLQConfig) ProtoMessage() {}

func (x *DLQConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_executor_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DLQConfig.ProtoReflect.Descriptor instead.
func (*DLQConfig) Descriptor() ([]byte, []int) {
	return file_proto_task_executor_proto_rawDescGZIP(), []int{24}
}

func (x *DLQConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *DLQConfig) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ExecutorName  string                 `protobuf:"bytes,2,opt,name=executor_name,json=executorName,proto3" json:"executor_name,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Status        TaskStatus             `protobuf:"varint,5,opt,name=status,proto3,enum=taskexecutor.TaskStatus" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	RetryCount    int32                  `protobuf:"varint,7,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_proto_task_executor_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_executor_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_proto_task_executor_proto_rawDescGZIP(), []int{25}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetExecutorName() string {
	if x != nil {
		return x.ExecutorName
	}
	return ""
}

func (x *Task) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Task) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Task) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *Task) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Task) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *Task) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Task) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Task) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Task) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

// Order представляет заказ
type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Items         []*OrderItem           `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	Total         float64                `protobuf:"fixed64,4,opt,name=total,proto3" json:"total,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_proto_task_executor_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_executor_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_proto_task_executor_proto_rawDescGZIP(), []int{26}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Order) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Order) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Order) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Order) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Order) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// OrderItem представляет товар в заказе
type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_proto_task_executor_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_executor_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_proto_task_executor_proto_rawDescGZIP(), []int{27}
}

func (x *OrderItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *OrderItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItem) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_proto_task_executor_proto protoreflect.FileDescriptor

const file_proto_task_executor_proto_rawDesc = "" +
	"\n" +
	"\x19proto/task_executor.proto\x12\ftaskexecutor\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\xce\x01\n" +
	"\x0eAddTaskRequest\x12#\n" +
	"\rexecutor_name\x18\x01 \x01(\tR\fexecutorName\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12F\n" +
	"\bmetadata\x18\x03 \x03(\v2*.taskexecutor.AddTaskRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"9\n" +
	"\x0fAddTaskResponse\x12&\n" +
	"\x04task\x18\x01 \x01(\v2\x12.taskexecutor.TaskR\x04task\"&\n" +
	"\x14GetTaskStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"_\n" +
	"\x15GetTaskStatusResponse\x120\n" +
	"\x06status\x18\x01 \x01(\x0e2\x18.taskexecutor.TaskStatusR\x06status\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"[\n" +
	"\x17RegisterExecutorRequest\x12#\n" +
	"\rexecutor_name\x18\x01 \x01(\tR\fexecutorName\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\tR\bleaderId\"4\n" +
	"\x18RegisterExecutorResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"9\n" +
	"\x12GetNextTaskRequest\x12#\n" +
	"\rexecutor_name\x18\x01 \x01(\tR\fexecutorName\"=\n" +
	"\x13GetNextTaskResponse\x12&\n" +
	"\x04task\x18\x01 \x01(\v2\x12.taskexecutor.TaskR\x04task\"q\n" +
	"\x17UpdateTaskStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x120\n" +
	"\x06status\x18\x02 \x01(\x0e2\x18.taskexecutor.TaskStatusR\x06status\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"B\n" +
	"\x18UpdateTaskStatusResponse\x12&\n" +
	"\x04task\x18\x01 \x01(\v2\x12.taskexecutor.TaskR\x04task\"M\n" +
	"\x15CreateExecutorRequest\x124\n" +
	"\x06config\x18\x01 \x01(\v2\x1c.taskexecutor.ExecutorConfigR\x06config\"L\n" +
	"\x16CreateExecutorResponse\x122\n" +
	"\bexecutor\x18\x01 \x01(\v2\x16.taskexecutor.ExecutorR\bexecutor\"]\n" +
	"\x15UpdateExecutorRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x124\n" +
	"\x06config\x18\x02 \x01(\v2\x1c.taskexecutor.ExecutorConfigR\x06config\"L\n" +
	"\x16UpdateExecutorResponse\x122\n" +
	"\bexecutor\x18\x01 \x01(\v2\x16.taskexecutor.ExecutorR\bexecutor\"$\n" +
	"\x12GetExecutorRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"I\n" +
	"\x13GetExecutorResponse\x122\n" +
	"\bexecutor\x18\x01 \x01(\v2\x16.taskexecutor.ExecutorR\bexecutor\"R\n" +
	"\x14ListExecutorsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"u\n" +
	"\x15ListExecutorsResponse\x124\n" +
	"\texecutors\x18\x01 \x03(\v2\x16.taskexecutor.ExecutorR\texecutors\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"'\n" +
	"\x15DeleteExecutorRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x18\n" +
	"\x16DeleteExecutorResponse\"\xf4\x01\n" +
	"\bExecutor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\x124\n" +
	"\x06config\x18\x04 \x01(\v2\x1c.taskexecutor.ExecutorConfigR\x06config\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xf5\x01\n" +
	"\x0eExecutorConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\x12?\n" +
	"\rwrite_concern\x18\x03 \x01(\v2\x1a.taskexecutor.WriteConcernR\fwriteConcern\x12<\n" +
	"\fretry_policy\x18\x04 \x01(\v2\x19.taskexecutor.RetryPolicyR\vretryPolicy\x126\n" +
	"\n" +
	"dlq_config\x18\x05 \x01(\v2\x17.taskexecutor.DLQConfigR\tdlqConfig\"E\n" +
	"\fWriteConcern\x125\n" +
	"\x05level\x18\x01 \x01(\x0e2\x1f.taskexecutor.WriteConcernLevelR\x05level\"\x9a\x01\n" +
	"\vRetryPolicy\x121\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1d.taskexecutor.RetryPolicyTypeR\x04type\x12!\n" +
	"\fmax_attempts\x18\x02 \x01(\x05R\vmaxAttempts\x125\n" +
	"\binterval\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\binterval\"D\n" +
	"\tDLQConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x02 \x01(\tR\tqueueName\"\xa3\x04\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rexecutor_name\x18\x02 \x01(\tR\fexecutorName\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12<\n" +
	"\bmetadata\x18\x04 \x03(\v2 .taskexecutor.Task.MetadataEntryR\bmetadata\x120\n" +
	"\x06status\x18\x05 \x01(\x0e2\x18.taskexecutor.TaskStatusR\x06status\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12\x1f\n" +
	"\vretry_count\x18\a \x01(\x05R\n" +
	"retryCount\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"started_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x83\x02\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12-\n" +
	"\x05items\x18\x03 \x03(\v2\x17.taskexecutor.OrderItemR\x05items\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x01R\x05total\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\\\n" +
	"\tOrderItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price*\xbb\x01\n" +
	"\x11WriteConcernLevel\x12#\n" +
	"\x1fWRITE_CONCERN_LEVEL_UNSPECIFIED\x10\x00\x12&\n" +
	"\"WRITE_CONCERN_REPLICA_ACKNOWLEDGED\x10\x01\x12\x1a\n" +
	"\x16WRITE_CONCERN_MAJORITY\x10\x02\x12 \n" +
	"\x1cWRITE_CONCERN_UNACKNOWLEDGED\x10\x03\x12\x1b\n" +
	"\x17WRITE_CONCERN_JOURNALED\x10\x04*\x86\x01\n" +
	"\x0fRetryPolicyType\x12!\n" +
	"\x1dRETRY_POLICY_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15RETRY_POLICY_CONSTANT\x10\x01\x12\x17\n" +
	"\x13RETRY_POLICY_LINEAR\x10\x02\x12\x1c\n" +
	"\x18RETRY_POLICY_EXPONENTIAL\x10\x03*\xa7\x01\n" +
	"\n" +
	"TaskStatus\x12\x1b\n" +
	"\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13TASK_STATUS_PENDING\x10\x01\x12\x1b\n" +
	"\x17TASK_STATUS_IN_PROGRESS\x10\x02\x12\x19\n" +
	"\x15TASK_STATUS_COMPLETED\x10\x03\x12\x16\n" +
	"\x12TASK_STATUS_FAILED\x10\x04\x12\x13\n" +
	"\x0fTASK_STATUS_DLQ\x10\x052\x96\a\n" +
	"\x13TaskExecutorManager\x12F\n" +
	"\aAddTask\x12\x1c.taskexecutor.AddTaskRequest\x1a\x1d.taskexecutor.AddTaskResponse\x12X\n" +
	"\rGetTaskStatus\x12\".taskexecutor.GetTaskStatusRequest\x1a#.taskexecutor.GetTaskStatusResponse\x12a\n" +
	"\x10RegisterExecutor\x12%.taskexecutor.RegisterExecutorRequest\x1a&.taskexecutor.RegisterExecutorResponse\x12R\n" +
	"\vGetNextTask\x12 .taskexecutor.GetNextTaskRequest\x1a!.taskexecutor.GetNextTaskResponse\x12a\n" +
	"\x10UpdateTaskStatus\x12%.taskexecutor.UpdateTaskStatusRequest\x1a&.taskexecutor.UpdateTaskStatusResponse\x12[\n" +
	"\x0eCreateExecutor\x12#.taskexecutor.CreateExecutorRequest\x1a$.taskexecutor.CreateExecutorResponse\x12[\n" +
	"\x0eUpdateExecutor\x12#.taskexecutor.UpdateExecutorRequest\x1a$.taskexecutor.UpdateExecutorResponse\x12R\n" +
	"\vGetExecutor\x12 .taskexecutor.GetExecutorRequest\x1a!.taskexecutor.GetExecutorResponse\x12X\n" +
	"\rListExecutors\x12\".taskexecutor.ListExecutorsRequest\x1a#.taskexecutor.ListExecutorsResponse\x12[\n" +
	"\x0eDeleteExecutor\x12#.taskexecutor.DeleteExecutorRequest\x1a$.taskexecutor.DeleteExecutorResponseB7Z5github.com/botashev/tasks-executor/proto/taskexecutorb\x06proto3"

var (
	file_proto_task_executor_proto_rawDescOnce sync.Once
	file_proto_task_executor_proto_rawDescData []byte
)

func file_proto_task_executor_proto_rawDescGZIP() []byte {
	file_proto_task_executor_proto_rawDescOnce.Do(func() {
		file_proto_task_executor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_task_executor_proto_rawDesc), len(file_proto_task_executor_proto_rawDesc)))
	})
	return file_proto_task_executor_proto_rawDescData
}

var file_proto_task_executor_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_task_executor_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_proto_task_executor_proto_goTypes = []any{
	(WriteConcernLevel)(0),           // 0: taskexecutor.WriteConcernLevel
	(RetryPolicyType)(0),             // 1: taskexecutor.RetryPolicyType
	(TaskStatus)(0),                  // 2: taskexecutor.TaskStatus
	(*AddTaskRequest)(nil),           // 3: taskexecutor.AddTaskRequest
	(*AddTaskResponse)(nil),          // 4: taskexecutor.AddTaskResponse
	(*GetTaskStatusRequest)(nil),     // 5: taskexecutor.GetTaskStatusRequest
	(*GetTaskStatusResponse)(nil),    // 6: taskexecutor.GetTaskStatusResponse
	(*RegisterExecutorRequest)(nil),  // 7: taskexecutor.RegisterExecutorRequest
	(*RegisterExecutorResponse)(nil), // 8: taskexecutor.RegisterExecutorResponse
	(*GetNextTaskRequest)(nil),       // 9: taskexecutor.GetNextTaskRequest
	(*GetNextTaskResponse)(nil),      // 10: taskexecutor.GetNextTaskResponse
	(*UpdateTaskStatusRequest)(nil),  // 11: taskexecutor.UpdateTaskStatusRequest
	(*UpdateTaskStatusResponse)(nil), // 12: taskexecutor.UpdateTaskStatusResponse
	(*CreateExecutorRequest)(nil),    // 13: taskexecutor.CreateExecutorRequest
	(*CreateExecutorResponse)(nil),   // 14: taskexecutor.CreateExecutorResponse
	(*UpdateExecutorRequest)(nil),    // 15: taskexecutor.UpdateExecutorRequest
	(*UpdateExecutorResponse)(nil),   // 16: taskexecutor.UpdateExecutorResponse
	(*GetExecutorRequest)(nil),       // 17: taskexecutor.GetExecutorRequest
	(*GetExecutorResponse)(nil),      // 18: taskexecutor.GetExecutorResponse
	(*ListExecutorsRequest)(nil),     // 19: taskexecutor.ListExecutorsRequest
	(*ListExecutorsResponse)(nil),    // 20: taskexecutor.ListExecutorsResponse
	(*DeleteExecutorRequest)(nil),    // 21: taskexecutor.DeleteExecutorRequest
	(*DeleteExecutorResponse)(nil),   // 22: taskexecutor.DeleteExecutorResponse
	(*Executor)(nil),                 // 23: taskexecutor.Executor
	(*ExecutorConfig)(nil),           // 24: taskexecutor.ExecutorConfig
	(*WriteConcern)(nil),             // 25: taskexecutor.WriteConcern
	(*RetryPolicy)(nil),              // 26: taskexecutor.RetryPolicy
	(*DLQConfig)(nil),                // 27: taskexecutor.DLQConfig
	(*Task)(nil),                     // 28: taskexecutor.Task
	(*Order)(nil),                    // 29: taskexecutor.Order
	(*OrderItem)(nil),                // 30: taskexecutor.OrderItem
	nil,                              // 31: taskexecutor.AddTaskRequest.MetadataEntry
	nil,                              // 32: taskexecutor.Task.MetadataEntry
	(*timestamppb.Timestamp)(nil),    // 33: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),      // 34: google.protobuf.Duration
}
var file_proto_task_executor_proto_depIdxs = []int32{
	31, // 0: taskexecutor.AddTaskRequest.metadata:type_name -> taskexecutor.AddTaskRequest.MetadataEntry
	28, // 1: taskexecutor.AddTaskResponse.task:type_name -> taskexecutor.Task
	2,  // 2: taskexecutor.GetTaskStatusResponse.status:type_name -> taskexecutor.TaskStatus
	28, // 3: taskexecutor.GetNextTaskResponse.task:type_name -> taskexecutor.Task
	2,  // 4: taskexecutor.UpdateTaskStatusRequest.status:type_name -> taskexecutor.TaskStatus
	28, // 5: taskexecutor.UpdateTaskStatusResponse.task:type_name -> taskexecutor.Task
	24, // 6: taskexecutor.CreateExecutorRequest.config:type_name -> taskexecutor.ExecutorConfig
	23, // 7: taskexecutor.CreateExecutorResponse.executor:type_name -> taskexecutor.Executor
	24, // 8: taskexecutor.UpdateExecutorRequest.config:type_name -> taskexecutor.ExecutorConfig
	23, // 9: taskexecutor.UpdateExecutorResponse.executor:type_name -> taskexecutor.Executor
	23, // 10: taskexecutor.GetExecutorResponse.executor:type_name -> taskexecutor.Executor
	23, // 11: taskexecutor.ListExecutorsResponse.executors:type_name -> taskexecutor.Executor
	24, // 12: taskexecutor.Executor.config:type_name -> taskexecutor.ExecutorConfig
	33, // 13: taskexecutor.Executor.created_at:type_name -> google.protobuf.Timestamp
	33, // 14: taskexecutor.Executor.updated_at:type_name -> google.protobuf.Timestamp
	25, // 15: taskexecutor.ExecutorConfig.write_concern:type_name -> taskexecutor.WriteConcern
	26, // 16: taskexecutor.ExecutorConfig.retry_policy:type_name -> taskexecutor.RetryPolicy
	27, // 17: taskexecutor.ExecutorConfig.dlq_config:type_name -> taskexecutor.DLQConfig
	0,  // 18: taskexecutor.WriteConcern.level:type_name -> taskexecutor.WriteConcernLevel
	1,  // 19: taskexecutor.RetryPolicy.type:type_name -> taskexecutor.RetryPolicyType
	34, // 20: taskexecutor.RetryPolicy.interval:type_name -> google.protobuf.Duration
	32, // 21: taskexecutor.Task.metadata:type_name -> taskexecutor.Task.MetadataEntry
	2,  // 22: taskexecutor.Task.status:type_name -> taskexecutor.TaskStatus
	33, // 23: taskexecutor.Task.created_at:type_name -> google.protobuf.Timestamp
	33, // 24: taskexecutor.Task.updated_at:type_name -> google.protobuf.Timestamp
	33, // 25: taskexecutor.Task.started_at:type_name -> google.protobuf.Timestamp
	33, // 26: taskexecutor.Task.completed_at:type_name -> google.protobuf.Timestamp
	30, // 27: taskexecutor.Order.items:type_name -> taskexecutor.OrderItem
	33, // 28: taskexecutor.Order.created_at:type_name -> google.protobuf.Timestamp
	33, // 29: taskexecutor.Order.updated_at:type_name -> google.protobuf.Timestamp
	3,  // 30: taskexecutor.TaskExecutorManager.AddTask:input_type -> taskexecutor.AddTaskRequest
	5,  // 31: taskexecutor.TaskExecutorManager.GetTaskStatus:input_type -> taskexecutor.GetTaskStatusRequest
	7,  // 32: taskexecutor.TaskExecutorManager.RegisterExecutor:input_type -> taskexecutor.RegisterExecutorRequest
	9,  // 33: taskexecutor.TaskExecutorManager.GetNextTask:input_type -> taskexecutor.GetNextTaskRequest
	11, // 34: taskexecutor.TaskExecutorManager.UpdateTaskStatus:input_type -> taskexecutor.UpdateTaskStatusRequest
	13, // 35: taskexecutor.TaskExecutorManager.CreateExecutor:input_type -> taskexecutor.CreateExecutorRequest
	15, // 36: taskexecutor.TaskExecutorManager.UpdateExecutor:input_type -> taskexecutor.UpdateExecutorRequest
	17, // 37: taskexecutor.TaskExecutorManager.GetExecutor:input_type -> taskexecutor.GetExecutorRequest
	19, // 38: taskexecutor.TaskExecutorManager.ListExecutors:input_type -> taskexecutor.ListExecutorsRequest
	21, // 39: taskexecutor.TaskExecutorManager.DeleteExecutor:input_type -> taskexecutor.DeleteExecutorRequest
	4,  // 40: taskexecutor.TaskExecutorManager.AddTask:output_type -> taskexecutor.AddTaskResponse
	6,  // 41: taskexecutor.TaskExecutorManager.GetTaskStatus:output_type -> taskexecutor.GetTaskStatusResponse
	8,  // 42: taskexecutor.TaskExecutorManager.RegisterExecutor:output_type -> taskexecutor.RegisterExecutorResponse
	10, // 43: taskexecutor.TaskExecutorManager.GetNextTask:output_type -> taskexecutor.GetNextTaskResponse
	12, // 44: taskexecutor.TaskExecutorManager.UpdateTaskStatus:output_type -> taskexecutor.UpdateTaskStatusResponse
	14, // 45: taskexecutor.TaskExecutorManager.CreateExecutor:output_type -> taskexecutor.CreateExecutorResponse
	16, // 46: taskexecutor.TaskExecutorManager.UpdateExecutor:output_type -> taskexecutor.UpdateExecutorResponse
	18, // 47: taskexecutor.TaskExecutorManager.GetExecutor:output_type -> taskexecutor.GetExecutorResponse
	20, // 48: taskexecutor.TaskExecutorManager.ListExecutors:output_type -> taskexecutor.ListExecutorsResponse
	22, // 49: taskexecutor.TaskExecutorManager.DeleteExecutor:output_type -> taskexecutor.DeleteExecutorResponse
	40, // [40:50] is the sub-list for method output_type
	30, // [30:40] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_proto_task_executor_proto_init() }
func file_proto_task_executor_proto_init() {
	if File_proto_task_executor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_task_executor_proto_rawDesc), len(file_proto_task_executor_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_task_executor_proto_goTypes,
		DependencyIndexes: file_proto_task_executor_proto_depIdxs,
		EnumInfos:         file_proto_task_executor_proto_enumTypes,
		MessageInfos:      file_proto_task_executor_proto_msgTypes,
	}.Build()
	File_proto_task_executor_proto = out.File
	file_proto_task_executor_proto_goTypes = nil
	file_proto_task_executor_proto_depIdxs = nil
}
